[package]
name = "chopsticks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
itertools = "0.4"
rand = "0.8"

[[bin]]
name = "sandbox"
path = "src/bin/sandbox.rs"
